name: noyaux

description: "A new Flutter package project."

version: 0.0.1

homepage: lisocash

publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  app:
    path: ../app

  dashboard:
    path: ../dashboard

  http: ^1.1.2
  share_plus: ^7.0.2
  flutter_spinkit: ^5.1.0
  get_ip_address: ^0.0.5
  country_ip: ^3.0.0
  cached_network_image: ^3.2.3
  material_design_icons_flutter: ^7.0.7296
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4
  image_picker: ^1.0.0
  shared_preferences: ^2.0.7
  permission_handler: ^11.1.0
  flutter_rounded_date_picker: ^3.0.2
  country_code_picker: ^3.0.0
  file_picker: ^6.1.1
  photo_view: ^0.14.0
  email_validator: ^2.0.1
  flutter_typeahead: ^5.0.1
  url_launcher: ^6.0.10
  flutter_local_notifications: ^17.0.0
  mobile_scanner: ^5.1.0
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.66.1
  flutter_stripe: ^10.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
